[workspace]
resolver = "2"
members = [
    "crates/litepack-core",
    "crates/litepack-cli",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = ""

[workspace.dependencies]
thiserror = "2.0.19"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
walkdir = "2.5.0"
zip = "8.6.0"
sevenz-rust2 = { version = "0.21.4", default-features = false, features = ["compress", "deflate", "lz4", "zstd", "aes256", "util"] }
rayon = "1.12.0"
parking_lot = "0.12.5"
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
indicatif = "0.18.6"

[profile.release]
lto = true
strip = true
