[package]
name = "litepack-gui"
version = "0.1.0"
description = "LitePack 桌面应用（Tauri v2 + Vue3）"
authors = ["_zhiqiu"]
license.workspace = true
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "litepack_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
litepack-core = { path = "../../litepack-core" }
litepack-cli = { path = "../../litepack-cli" }
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-fs = "2.5.1"
tauri-plugin-log.workspace = true
log.workspace = true
parking_lot.workspace = true
path-slash.workspace = true
urlencoding.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
windows-sys = { version = "0.60.0", features = ["Win32_UI_Shell", "Win32_System_Console"] }
